### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by jrenaf** [HKUST-RML/soft_gripper_page_turning#2]
In readme.md 
change 

- `rosrun soft_gripper_page_turning soft_gripper_frame.py ` to `rosrun a4_paper_turning soft_gripper_frame.py` 

and

- `rosrun soft_gripper_page_turning page_turning_1D_aug_demo.py` to  `rosrun a4_paper_turning page_turning_1D_aug_demo.py `

as the package name stated in [package.xml](https://github.com/HKUST-RML/flexflip/blob/master/package.xml ) is `a4_paper_turning` rather `soft_gripper_page_turning`

**Comment by ZachJiang** [comment]
Solved, package name updated
